export enum States {
  SWITCH_DEFENSE = 'SwitchDefense',
  HELP_DEFENSE = 'HelpDefense',
  FIGHT_OVER_SCREEN = 'FightOverScreen',
  DEFEND_MAN = 'DefendMan',
  IDLE = 'Idle',
  CHASE_REBOUND = 'ChaseRebound',
  SET_SCREEN = 'SetScreen',
  GO_BACK_TO_SPOT = 'GoBackToSpot',
  SHOOTING = 'Shooting',
  CONTEST_SHOT = 'ContestShot',
  BLOCK_SHOT = 'BlockShot',
  PASSING = 'Passing',
  LAYUP = 'Layup',
  DUNK = 'Dunk',
  DRIBBLE_TO_POINT = 'DribbleToPoint',
  DRIVE_TO_BASKET = 'DriveToBasket',
  PLAYER_CONTROL = 'PlayerControl',
  FUMBLE = 'Fumble',
  FALL = 'Fall',
  STEAL = 'Steal',
  CROSSOVER = 'Crossover',
}
